Wheretoget-Webapi/Controllers/HomeController.cs
using System.Linq;
using System.Web.Mvc;
using DataLayer.Context;

namespace Wheretoget_Webapi.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            ViewBag.Title = "Home Page";
            //var db = new WheretogetContext();
            //var user = db.User.ToList();
            return View();
        }
    }
}

Wheretoget-Webapi/Controllers/PostController.cs
using DataLayer.Constant;
using HtmlAgilityPack;
using Repository.Dtos;
using Repository.Interfaces;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Threading.Tasks;
using System.Web;
using System.Web.Http;

namespace Wheretoget_Webapi.Controllers
{
    //[Authorize]
    public class PostController : ApiController
    {
		private readonly IPostRepository _repo;
		public PostController(IPostRepository repo)
		{
			this._repo=repo;
		}
        public async Task<ApiResponse> CreatePostAndResource()
        {
            ApiResponse result=null;
            // Check if the request contains multipart/form-data.
            if (!Request.Content.IsMimeMultipartContent())
            {
                result = new ApiResponse(HttpStatusCode.UnsupportedMediaType, "Unsupported mediaType");
            }
            var prefixList = new[] { "jpg", "jpeg", "png", "bmp", "gif" };
            string root = HttpContext.Current.Server.MapPath("~/Resources");
            var provider = new MultipartFormDataStreamProvider(root);

            try
            {
                // Read the form data.
                await Request.Content.ReadAsMultipartAsync(provider);

                //image mimetype control with file
                if (prefixList.Any(r => provider.FileData[0].Headers.ContentType.ToString().EndsWith(r)))
                {
                // This illustrates how to get the file names.
                    foreach (MultipartFileData file in provider.FileData)
                    {
                        CreatePostDto post = new CreatePostDto
                        {
                            Name = provider.FileData[0].Headers.ContentDisposition.FileName,
                            Path = file.LocalFileName,
                            Description = provider.FormData["description"],
                            Title = provider.FormData["title"],
                            MimeType = provider.FileData[0].Headers.ContentType.ToString(),
                            AuthorId = Guid.Parse("4DD72FD1-2324-E611-9C1B-9439E59F5D00") //Change to row

                        };
                        await _repo.CreatePostAndReesource(post);

                    }

                    result = new ApiResponse(HttpStatusCode.Accepted, "Resource create successfull");
                }
            }
            catch (Exception e)
            {
                result = new ApiResponse(HttpStatusCode.InternalServerError, e.Message);
            }
            return result;
        }

       
    }
}

Wheretoget-Webapi/Views/Home/Index.cshtml
<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS, and JavaScript.</p>
    <p><a href="http://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>
<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET Web API is a framework that makes it easy to build HTTP services that reach
            a broad range of clients, including browsers and mobile devices. ASP.NET Web API
            is an ideal platform for building RESTful applications on the .NET Framework.
        </p>
        <p><a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkId=301870">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkId=301871">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkId=301872">Learn more &raquo;</a></p>
    </div>
</div>
<form name="form1" method="post" enctype="multipart/form-data" action="@Url.Action("CreatePostAndResource","Post",new { httproute = "DefaultApi" })">
    <div>
        <label for="caption">Image Caption</label>
        <input name="caption" type="text" />
    </div>
    <div>
        <label for="image1">Image File</label>
        <input name="image1" type="file" />
    </div>
    <div>
        <label for="Description">Description</label>
        <input name="Description" type="text" />
    </div>
    <div>
        <label for="Title">Title</label>
        <input name="Title" type="text" />
    </div>
    <div>
        <label for="Comment">Comment</label>
        <input name="Comment" type="text" />
    </div>
    <div>
        <input type="submit" value="Submit" />
    </div>
</form>